### ISSUE TITLE
Issue with generic ores

### ISSUE THREAD

**Issue by bell07** [joe7575/Minetest-Gravelsieve#5]
After last changes I get the error
`2018-01-04 07:37:53: ERROR[Main]: ServerError: AsyncErr: environment_Step: Runtime error from mod 'gravelsieve' in callback environment_Step(): ...t/games/mygame/mods/utils-mymodpack/gravelsieve/init.lua:58: attempt to perform arithmetic on field 'clust_scarcity' (a nil value)
`
Maybe you need an additional check if clust_scarcity is set for all ores.

Additional note: I implemented some similar logic for unternull ore-enabled lava-cooling some times ago:
https://github.com/CasimirKaPazi/unternull/blob/master/additional_stuff/init.lua#L145
I do not know why in detail but I used the check ore_type == "scatter" to be sure the relevant ores only are selected. Adding this check should solve the problem with generated lot of "granit ore" stones reported by RSLRedstonier in forum. The granit is not "scatter". .. And it should solve this issue with clust_scarcity ;-)

**Comment by joe7575** [comment]
I added both checks to be on the safe side: ore_type == "scatter" and clust_scarcity > 0

**Comment by bell07** [comment]
I see you do not check and `drop ~= item.ore` anymore. So do you like to remove all drop-check code? Or is it a misstake?

**Comment by joe7575** [comment]
The result keeps the same, with or without this check. But I added the line again.
